/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Contenedores;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JDesktopPane;

/**
 *
 * @author admin
 */
public class DesktopPaneZ extends JDesktopPane {
    Image imagenfondo;
    /**
     * Creates new form DesktopPaneZ
     */
    public DesktopPaneZ() {
        initComponents();
    }

    public Image getImagenfondo() {
        return imagenfondo;
    }

    public void setImagenfondo(Image imagenfondo) {
        this.imagenfondo = imagenfondo;
        repaint();
    }

    @Override
    public void paint(Graphics grphcs) {
        if(imagenfondo != null){
            grphcs.drawImage(imagenfondo, 0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
        }else{
            setOpaque(true);
        }
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 247, 162));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
