/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Contenedores;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JToolBar;

/**
 *
 * @author admin
 */
public class ToolBarz extends JToolBar {

    /**
     * Creates new form ToolBarz
     */
    public ToolBarz() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(127, 179, 213));
        setForeground(new java.awt.Color(29, 32, 98));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void botonEnfoque(JButton boton) {
       boton.setBackground(new Color(132,132,241));
       boton.setForeground(new Color(0, 0, 0));
    }
    private void botonDesenfoque(JButton boton){
       boton.setBackground(new Color(0,51,102));
       boton.setForeground(new Color(255, 255, 255)); 
    }
}
