/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing.Controles;

import javax.swing.JList;

/**
 *
 * @author Dell Inspiron
 */
public class ListZ extends JList {

    /** Creates new form ListZ */
    public ListZ() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(89, 24, 24));
        setBorder(null);
        setForeground(java.awt.Color.white);
        setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "SAMPLE1", "SAMPLE2", "SAMPLE3", "SAMPLE4" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
