/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Controles;

import javax.swing.JRadioButton;

/**
 *
 * @author Dell Inspiron
 */
public class RadioButtonZ extends JRadioButton {

    /**
     * Creates new form RadioButtonZ
     */
    public RadioButtonZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();

        jToolBar1.setRollover(true);

        setBackground(new java.awt.Color(255, 247, 162));
        setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        setForeground(new java.awt.Color(29, 32, 98));
        setText("SAMPLE");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
