/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.Controles;

import javax.swing.JSlider;

/**
 *
 * @author Dell Inspiron
 */
public class SliderZ extends JSlider {

    /**
     * Creates new form SliderZ
     */
    public SliderZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 247, 162));
        setForeground(new java.awt.Color(29, 32, 98));
        setPaintLabels(true);
        setPaintTicks(true);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
